### PR TITLE
Add option to proxy everything by default

### PR DESCRIPTION
**Pull request by lookyman**
ping @TomasVotruba

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Awesome job! Thank you.

Could you also add failing test of what you described on Twitter?

**Comment by lookyman** [comment]
Yup, I wanted to write more tests anyway..

**Comment by lookyman** [comment]
So far I've discovered that that bug is caused by https://ocramius.github.io/ProxyManager/docs/lazy-loading-value-holder.html#known-limitations and https://api.nette.org/2.4/source-Http.Request.php.html#103. Not much we can do with that, I guess.

**Comment by TomasVotruba** [comment]
Is that only single issue? If so, you could send PR to [Nette\Http](http://github.com/nette/http).

Also, I would add temporary workaround to exclude these services.

**Comment by TomasVotruba** [comment]
Awesome! :)

**Pull request merged**
